version: "2.4"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.1-legacy
    container_name: keycloak
    command: ["-Djboss.socket.binding.port-offset=5",
              "-Dkeycloak.profile.feature.upload_scripts=enabled"]
    volumes:
      - ./src/main/resources/docker/keycloak/realm-config:/realms
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/realms/CONTROL-E-realm.json
    ports:
      - 8085:8085

networks:
  control-e-net:
    name: control-e-net
