server:
  port: 8080
  servlet:
    context-path: /control-e
spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_3e40d7289404914?reconnect=true
    username: b34ba572935e61
    password: 48a16bcbd174f15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    br:
      jus: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    supported-submit-methods: ['get', 'post', 'put', 'delete', 'patch', 'options']
  packages-to-scan: com.control.e.modulo.colacao.rest
