---
server:
  port: 8080
  servlet:
    context-path: /control-e

---
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_3e40d7289404914?reconnect=true
    username: b34ba572935e61
    password: 48a16bcbd174f15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    br:
      jus: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG

---
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    supported-submit-methods: ['get', 'post', 'put', 'delete', 'patch', 'options']
  packages-to-scan: com.control.e.modulo.colacao.rest

---
keycloak:
  auth-server-url: http://localhost:8085/auth
  bearer-only: true
  config:
    base-url: http://localhost:4200/
    valid-redirect-url: http://localhost:4200/*
    backend-id: control-e-backend
    frontend-id: control-e-frontend
  credentials:
    secret: f541e548-ff50-4c97-928d-f296fcd7be9c
  realm: CONTROL-E
  resource: control-e-backend
  ssl-required: external
  use-resource-role-mappings: true
